name: Deploy Cloud Function GetGameItem to Yandex Cloud
on:
  push:
    branches:
      - 'ci/github-actions' # Срабатывает при пуше в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Проверяем ключи
      - name: Validate secrets
        run: |
         echo "YC_FOLDER_ID: '${YC_FOLDER_ID}'"
         echo "DB_KEY: '${DB_KEY}'"
         if [ -z "$YC_FOLDER_ID" ]; then echo "ERROR: YC_FOLDER_ID is missing!" && exit 1; fi
         if [ -z "$DB_KEY" ]; then echo "ERROR: DB_KEY is missing!" && exit 1; fi
        env:
         YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
         DB_KEY: ${{ secrets.DB_KEY }}


      # 3. Деплоим код в Яндекс Облако
      - name: Deploy Serverless Function
        uses: yc-actions/yc-sls-function@v5
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_SERVICE_AC_KEY }}
          bucket: ${{ secrets.YC_BUCKET }}
          # Настройки функции
          folder-id: ${{ secrets.YC_FOLDER_ID }} # ID каталога в облаке
          function-name: 'arz-get-item-function'  # Имя функции в консоли Яндекса
          runtime: 'golang121'                    # Окружение (например: nodejs18, python311, go121)
          entrypoint: 'main.GetItem'            # Точка входа (файл.экспортируемая_функция)
          execution-timeout: '5'                 # Таймаут выполнения в секундах
          environment: |
            DATABASE_KEY=${{ secrets.DB_KEY }}
